module:
  _target_: geoarches.utils.normalization.NormalizationStatistics
  variables: 
    surface:
        - 10m_u_component_of_wind
        - 10m_v_component_of_wind
        - 2m_temperature
        - mean_sea_level_pressure
    level:
        - geopotential
        - u_component_of_wind 
        - v_component_of_wind
        - temperature
        - specific_humidity
        - vertical_velocity
  loss_weight_per_variable:
    surface: [0.1, 0.1, 1.0, 0.1]
    level: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  levels: [50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
  norm_scheme: pangu

loss_coeffs:
  latitude: 121
  pow: 2
  use_weatherbench_lat_coeffs: true 
  loss_delta_normalization: true
